"""Compare the naked option-selling strategies with their hedged (credit-spread) variants.

    python3 scripts/compare_hedged.py                                # same window as run_backtest.py
    python3 scripts/compare_hedged.py --start 2026-07-27 --end 2026-09-25 --widths 200 300
    python3 scripts/compare_hedged.py --offline                      # only option data already in DuckDB

Wing contracts not yet in DuckDB are fetched from Breeze (needs today's session
token), like the sold legs in run_backtest.py. Writes reports/naked_vs_hedged.md
and reports/naked_vs_hedged_metrics.csv.
"""
import argparse
import sys
from datetime import timedelta
from pathlib import Path

import _path  # noqa: F401

from backtest.compare import markdown_table, summarize, write_csv
from backtest.data import DataFeed
from backtest.hedged import HedgedStrategy, HedgeParams
from backtest.margin import MarginModel
from backtest.strategies import RangeBreakoutSeller, ZeroDteStraddleSeller
from trading_data.app import bootstrap, connect_client, parse_date
from trading_data.log import get_logger


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--underlying", default="NIFTY")
    ap.add_argument("--start", type=parse_date)
    ap.add_argument("--end", type=parse_date)
    ap.add_argument("--widths", type=int, nargs="+", default=[200, 300], help="wing distances in points")
    ap.add_argument("--offline", action="store_true", help="do not call Breeze for missing option data")
    ap.add_argument("--out", help="markdown path (default reports/naked_vs_hedged.md)")
    args = ap.parse_args()

    settings, store = bootstrap("compare_hedged")
    log = get_logger("compare_hedged")
    probe = DataFeed(settings, store, args.underlying)
    last = store.market_coverage(probe.instrument.name, probe.instrument.exchange, "1minute")[1]
    end = args.end or last
    start = args.start or probe.cal.next_trading_day(end - timedelta(days=61), include_self=True)
    client = None if args.offline else connect_client(settings, store)
    feed = DataFeed(settings, store, args.underlying, client)
    feed.load_spot(start - timedelta(days=90), end)
    model = MarginModel()

    rows, missing = [], []
    for cls in (RangeBreakoutSeller, ZeroDteStraddleSeller):
        naked = cls(feed)
        rows.append(summarize(naked.name, "naked", naked.run(start, end), model))
        for w in args.widths:
            hedged = HedgedStrategy(cls(feed), HedgeParams(wing_points=w))
            rows.append(summarize(naked.name, f"hedged {w}pt", hedged.run(start, end), model))
            missing += [dict(m, variant=hedged.name) for m in hedged.missing]
        for r in rows[-1 - len(args.widths):]:
            log.info("%s [%s]: %d trades, net %.0f, max DD %.0f, capital %.0f", r["strategy"], r["variant"],
                     r["trades"], r["net_pnl"], r["max_drawdown"], r["capital_est"])

    out = args.out or str(settings.paths.report_dir / "naked_vs_hedged.md")
    csv_path = out.rsplit(".", 1)[0] + "_metrics.csv"
    write_csv(csv_path, rows)
    with open(out, "w") as fh:
        fh.write(render(args.underlying, start, end, feed, model, rows, missing, csv_path))
    print(markdown_table(rows))
    print(f"\nReport: {out}\nCSV:    {csv_path}")
    if missing:
        print(f"WARNING: {len(missing)} wing(s) had no price data; those positions are counted unhedged.")
    if client:
        print(f"Breeze API calls this run: {client.budget.used_this_run}")
    store.close()
    return 0


def render(underlying, start, end, feed, model, rows, missing, csv_path) -> str:
    lot = feed.profile.lot_size
    miss = ("\n".join(f"- {m['variant']}: {m['right']} {m['strike']:g} exp {m['expiry']} "
                      f"(position {m['position']}, no {m['missing']} price)" for m in missing)
            if missing else "None: every wing had a real traded price at the sold leg's entry and exit minute.")
    return f"""# Naked vs hedged option selling — {underlying}, {start} to {end}

Generated by `scripts/compare_hedged.py`. Metrics CSV: `{Path(csv_path).name}`.

## Comparison

{markdown_table(rows)}

*Trades* are positions: a sold leg and its wing count as one trade, so naked and hedged
have the same count. All P&L figures are net of costs unless labelled gross.
Margin/capital columns are **estimates** (see below), not broker numbers.

## What was compared

- **Naked** = the existing strategies, unchanged (`backtest/strategies.py`).
- **Hedged Npt** = same strategy instance, identical entries, exits, stops and
  re-entries, plus one bought wing per sold leg, N points further OTM
  (sold PUT K → bought PUT K−N; sold CALL K → bought CALL K+N), opened at the
  sold leg's entry minute and closed at its exit minute (`backtest/hedged.py`).
  Positional becomes a bull-put / bear-call credit spread; 0DTE becomes an iron
  fly/condor around the ITM-100 legs.
- Size: 5 lots × {lot} = {5 * lot} qty per leg (both variants).

## Pricing, costs, margin

- **Option prices are real** Breeze 1-minute NIFTY option candles stored in DuckDB,
  for both the sold legs and the wings (no Black-Scholes/delta model). When a
  contract did not trade in a given minute, the last traded price before it is
  used (same rule for both legs).
- **Costs** (identical `CostModel` for every leg, both variants): ₹20/order
  brokerage, STT 0.1% on sell premium, NSE txn 0.03503%, SEBI ₹10/crore,
  stamp 0.003% on buys, GST 18% on brokerage+exchange+SEBI, slippage 0.5 pt
  per side per unit. A hedged position pays these on 4 orders instead of 2.
- **Margin (estimate)**: SPAN ≈ {model.span_pct}% of notional per naked short,
  capped at wing width × qty for a hedged short; calls and puts offset (the larger
  side is charged); exposure {model.exposure_pct}% of notional on every short.
  *Capital* = margin + wing premium paid. Peak is taken over the open book at every
  entry. Real SPAN files and Zerodha's basket-margin API will differ; the live adapter
  (`zerodha/margin.py`) queries the real number before any order.
- **Max loss / trade (defined)**: hedged = (width − net credit) × qty + that position's
  costs. Naked = unbounded (stops limit it in practice but can gap; see Largest loss).

## Limitations

- Short sample (one ~2-month window, few trades); results are not statistically robust.
- Wing exits use the close of the exit minute; a 0DTE sold leg stopped intrabar fills
  at its stop price, so the wing may be marked slightly differently from a real fill.
- Deep-OTM wings can be illiquid; last-traded-price fallback can be stale.
- No assignment/physical-settlement effects are modelled (index options are cash-settled).
- The 0DTE entry time is chosen walk-forward on the naked P&L, so both variants share it.

## Wings without price data

{miss}
"""


if __name__ == "__main__":
    sys.exit(main())
